#!/usr/bin/env python3
"""
Route Definitions: CRM Integration Routes
Exposes REST endpoints for CRM ingestion: fetching leads, call transcripts, and agent metrics.
Tags: CRM Integration
Prefix: /api/crm/v1
"""

import logging
import datetime
import re
from typing import List, Dict, Any, Optional
from fastapi import APIRouter, HTTPException, Header, Query, Path, status
from pydantic import BaseModel, Field
from bson import ObjectId

from core.mongo_manager import mongo_db
from routes.agent_routes import find_agent_by_id_and_enterprise, build_enterprise_or_conditions, bson_safe
from core.agent_resolver import resolve_agent_config

logger = logging.getLogger(__name__)

router = APIRouter(
    prefix="/api/crm/v1",
    tags=["CRM Integration"],
    responses={
        401: {"description": "Unauthorized Access - Bearer token or Enterprise ID missing"},
        404: {"description": "Resource Not Found"},
        500: {"description": "Internal Server Error"}
    }
)

def parse_date_to_timestamp(date_str: str, is_end_of_day: bool = False) -> float | None:
    """Helper to parse 'YYYY-MM-DD' or ISO date strings to UNIX timestamp float."""
    if not date_str or not str(date_str).strip():
        return None
    ds = str(date_str).strip()
    try:
        if len(ds) == 10 and ds.count("-") == 2:
            if is_end_of_day:
                dt = datetime.datetime.strptime(f"{ds} 23:59:59", "%Y-%m-%d %H:%M:%S")
            else:
                dt = datetime.datetime.strptime(f"{ds} 00:00:00", "%Y-%m-%d %H:%M:%S")
            return dt.timestamp()
        dt = datetime.datetime.fromisoformat(ds.replace("Z", "+00:00"))
        return dt.timestamp()
    except Exception as e:
        logger.warning(f"Failed to parse date string '{date_str}': {e}")
        return None


@router.get(
    "/agents/{agentId}/leads",
    status_code=status.HTTP_200_OK,
    summary="Fetch all leads (CRM Integration)",
    description="Retrieve a clean list of leads generated by an AI agent for ingestion into a CRM system."
)
async def get_crm_agent_leads(
    agentId: str = Path(..., description="The unique ID of the AI Agent (agentId string or Mongo _id)"),
    startDate: Optional[str] = Query(None, description="Filter leads starting from this date (e.g., 2026-05-01)"),
    endDate: Optional[str] = Query(None, description="Filter leads up to this date (e.g., 2026-05-31)"),
    page: int = Query(1, ge=1, description="Page number for pagination"),
    limit: int = Query(50, ge=1, le=500, description="Number of leads per page"),
    enterprise_id: Optional[str] = Query(None, description="Enterprise ID query parameter"),
    x_enterprise_id: Optional[str] = Header(None, alias="x-enterprise-id", description="Enterprise ID header")
):
    ent_id = (enterprise_id or x_enterprise_id or "").strip()
    
    if mongo_db.client is None:
        return {"success": True, "total": 0, "page": page, "limit": limit, "leads": []}
        
    db = mongo_db.client.get_default_database()
    
    target_ids = [agentId]
    resolved_agent = await find_agent_by_id_and_enterprise(agentId, ent_id) if ent_id else await resolve_agent_config(agentId)
    if ent_id and not resolved_agent:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail={"success": False, "message": f"Agent '{agentId}' not found for enterprise '{ent_id}'"}
        )
    if resolved_agent:
        if resolved_agent.get("agentId"):
            target_ids.append(resolved_agent.get("agentId"))
        if resolved_agent.get("_id"):
            target_ids.append(str(resolved_agent.get("_id")))
            
    start_ts = parse_date_to_timestamp(startDate, is_end_of_day=False)
    end_ts = parse_date_to_timestamp(endDate, is_end_of_day=True)
    
    agent_clauses = []
    for tid in set(target_ids):
        agent_clauses.extend([
            {"agentId": tid},
            {"agent_id": tid},
            {"agent": tid}
        ])
        if ObjectId.is_valid(tid):
            agent_clauses.append({"_id": ObjectId(tid)})
            
    filt = {"$or": agent_clauses}

    leads_map = {}
    target_collections = ["Agent_Stream_CallsLogs", "outbound_calls", "aiagentcallreports"]
    
    for coll_name in target_collections:
        try:
            cursor = db[coll_name].find(filt)
            async for doc in cursor:
                doc_id = str(doc["_id"])
                if doc_id in leads_map:
                    continue
                    
                ts = doc.get("timestamp") or doc.get("createdAt") or doc.get("created_at") or 0
                ts_val = 0.0
                if isinstance(ts, (int, float)):
                    ts_val = float(ts)
                elif isinstance(ts, str):
                    try:
                        ts_val = datetime.datetime.fromisoformat(ts.replace("Z", "+00:00")).timestamp()
                    except Exception:
                        ts_val = 0.0
                elif isinstance(ts, datetime.datetime):
                    ts_val = ts.timestamp()
                    
                if start_ts is not None and ts_val < start_ts:
                    continue
                if end_ts is not None and ts_val > end_ts:
                    continue
                    
                phone = doc.get("virtualNumber") or doc.get("phone_number") or doc.get("caller_phone_no") or doc.get("lead_phone_no") or doc.get("to_number") or doc.get("from_number") or ""
                name = doc.get("customer_name") or doc.get("name") or doc.get("lead_name") or "Customer"
                email = doc.get("email") or doc.get("lead_email") or ""
                summary = doc.get("call_summary") or doc.get("summary") or ""
                meeting_consent = doc.get("caller_meeting_consent") or doc.get("meeting_consent") or False
                business_interest = doc.get("business_interest") or doc.get("car_model") or ""
                transcript = doc.get("transcript") or []
                call_id = doc.get("call_id") or doc.get("call_sid") or doc_id
                status_str = doc.get("status", "completed")
                duration = doc.get("duration") or doc.get("duration_seconds") or 0
                
                lead_entry = {
                    "id": doc_id,
                    "conversationId": call_id,
                    "agentId": agentId,
                    "enterpriseId": ent_id or doc.get("enterprise_id") or doc.get("enterprise"),
                    "name": name,
                    "phone": phone,
                    "email": email,
                    "summary": summary,
                    "meetingConsent": bool(meeting_consent),
                    "businessInterest": business_interest,
                    "status": status_str,
                    "durationSeconds": duration,
                    "timestamp": ts,
                    "transcript": transcript
                }
                leads_map[doc_id] = lead_entry
        except Exception as ex:
            logger.warning(f"Error querying collection '{coll_name}' for leads: {ex}")
            
    all_leads = list(leads_map.values())
    
    def get_ts(item):
        t = item.get("timestamp") or 0
        if isinstance(t, (int, float)):
            return float(t)
        if isinstance(t, str):
            try:
                return datetime.datetime.fromisoformat(t.replace("Z", "+00:00")).timestamp()
            except Exception:
                return 0.0
        return 0.0
        
    all_leads.sort(key=get_ts, reverse=True)
    total_count = len(all_leads)
    skip = (page - 1) * limit
    paginated_leads = all_leads[skip : skip + limit]
    
    return {
        "success": True,
        "total": total_count,
        "page": page,
        "limit": limit,
        "leads": paginated_leads
    }


@router.get(
    "/agents/conversations/{conversationId}/transcript",
    status_code=status.HTTP_200_OK,
    summary="Fetch call transcript (CRM Integration)",
    description="Retrieve the full transcript of a specific call by its conversationId."
)
async def get_crm_call_transcript(
    conversationId: str = Path(..., description="The unique conversation ID of the call (call_id, call_sid, or Mongo _id)"),
    enterprise_id: Optional[str] = Query(None, description="Enterprise ID query parameter"),
    x_enterprise_id: Optional[str] = Header(None, alias="x-enterprise-id", description="Enterprise ID header")
):
    if mongo_db.client is None:
        raise HTTPException(status_code=500, detail={"success": False, "message": "Database connection error"})
        
    db = mongo_db.client.get_default_database()
    
    id_clauses = [
        {"call_id": conversationId},
        {"callId": conversationId},
        {"call_sid": conversationId},
        {"_id": conversationId}
    ]
    if ObjectId.is_valid(conversationId):
        id_clauses.append({"_id": ObjectId(conversationId)})
        
    query = {"$or": id_clauses}
    
    target_collections = ["Agent_Stream_CallsLogs", "outbound_calls", "aiagentcallreports"]
    for coll_name in target_collections:
        try:
            doc = await db[coll_name].find_one(query)
            if doc:
                safe_doc = bson_safe(dict(doc))
                safe_doc["_id"] = str(safe_doc["_id"])
                return {
                    "success": True,
                    "conversationId": conversationId,
                    "transcript": safe_doc.get("transcript", []),
                    "call_details": safe_doc
                }
        except Exception as ex:
            logger.warning(f"Error querying collection '{coll_name}' for transcript: {ex}")
                
    raise HTTPException(
        status_code=status.HTTP_404_NOT_FOUND,
        detail={"success": False, "message": f"Transcript for conversationId '{conversationId}' not found"}
    )


@router.get(
    "/agents/{agentId}/metrics",
    status_code=status.HTTP_200_OK,
    summary="Fetch agent metrics (CRM Integration)",
    description="Retrieve high-level analytics like total calls, average duration, and business interest distributions for a given date range."
)
async def get_crm_agent_metrics(
    agentId: str = Path(..., description="The unique ID of the AI Agent"),
    startDate: Optional[str] = Query(None, description="Filter starting from this date (e.g., 2026-05-01)"),
    endDate: Optional[str] = Query(None, description="Filter up to this date (e.g., 2026-05-31)"),
    enterprise_id: Optional[str] = Query(None, description="Enterprise ID query parameter"),
    x_enterprise_id: Optional[str] = Header(None, alias="x-enterprise-id", description="Enterprise ID header")
):
    ent_id = (enterprise_id or x_enterprise_id or "").strip()
    
    if mongo_db.client is None:
        return {"success": True, "agentId": agentId, "metrics": {}}
        
    db = mongo_db.client.get_default_database()
    
    target_ids = [agentId]
    resolved_agent = await find_agent_by_id_and_enterprise(agentId, ent_id) if ent_id else await resolve_agent_config(agentId)
    if ent_id and not resolved_agent:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail={"success": False, "message": f"Agent '{agentId}' not found for enterprise '{ent_id}'"}
        )
    if resolved_agent:
        if resolved_agent.get("agentId"):
            target_ids.append(resolved_agent.get("agentId"))
        if resolved_agent.get("_id"):
            target_ids.append(str(resolved_agent.get("_id")))
            
    start_ts = parse_date_to_timestamp(startDate, is_end_of_day=False)
    end_ts = parse_date_to_timestamp(endDate, is_end_of_day=True)
    
    agent_clauses = []
    for tid in set(target_ids):
        agent_clauses.extend([
            {"agentId": tid},
            {"agent_id": tid},
            {"agent": tid}
        ])
        if ObjectId.is_valid(tid):
            agent_clauses.append({"_id": ObjectId(tid)})
            
    filt = {"$or": agent_clauses}

    seen_ids = set()
    total_calls = 0
    completed_calls = 0
    failed_calls = 0
    total_duration_sec = 0.0
    business_interests = {}
    languages_dist = {}

    target_collections = ["Agent_Stream_CallsLogs", "outbound_calls", "aiagentcallreports"]
    for coll_name in target_collections:
        try:
            cursor = db[coll_name].find(filt)
            async for doc in cursor:
                doc_id = str(doc["_id"])
                if doc_id in seen_ids:
                    continue
                seen_ids.add(doc_id)
                
                ts = doc.get("timestamp") or doc.get("createdAt") or doc.get("created_at") or 0
                ts_val = 0.0
                if isinstance(ts, (int, float)):
                    ts_val = float(ts)
                elif isinstance(ts, str):
                    try:
                        ts_val = datetime.datetime.fromisoformat(ts.replace("Z", "+00:00")).timestamp()
                    except Exception:
                        ts_val = 0.0
                elif isinstance(ts, datetime.datetime):
                    ts_val = ts.timestamp()
                    
                if start_ts is not None and ts_val < start_ts:
                    continue
                if end_ts is not None and ts_val > end_ts:
                    continue
                    
                total_calls += 1
                status_str = str(doc.get("status", "completed")).lower()
                if status_str in ["completed", "success", "answered"]:
                    completed_calls += 1
                else:
                    failed_calls += 1
                    
                duration = float(doc.get("duration") or doc.get("duration_seconds") or 0)
                total_duration_sec += duration
                
                b_interest = doc.get("business_interest") or doc.get("car_model") or "General"
                business_interests[b_interest] = business_interests.get(b_interest, 0) + 1
                
                lang = doc.get("language") or "en"
                if isinstance(lang, list) and lang:
                    lang = lang[0]
                languages_dist[str(lang)] = languages_dist.get(str(lang), 0) + 1
        except Exception as ex:
            logger.warning(f"Error computing metrics from '{coll_name}': {ex}")

    avg_duration = round(total_duration_sec / total_calls, 2) if total_calls > 0 else 0.0
    total_minutes = round(total_duration_sec / 60.0, 2)

    return {
        "success": True,
        "agentId": agentId,
        "enterpriseId": ent_id,
        "metrics": {
            "totalCalls": total_calls,
            "completedCalls": completed_calls,
            "failedCalls": failed_calls,
            "totalDurationMinutes": total_minutes,
            "averageDurationSeconds": avg_duration,
            "businessInterests": business_interests,
            "languages": languages_dist
        }
    }
