name: Voice AI Bot CD

on:
  workflow_run:
    workflows: ["Voice AI Bot CI"]
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Pull updated Docker image
        run: |
          sudo docker pull ${{ secrets.DOCKER_USERNAME }}/agent-stream-voice-agent:latest

      - name: Stop and remove old container
        run: |
          sudo docker rm -f voice-bot-container || true

      - name: Run new Docker container
        run: |
          sudo docker run -d \
            -p 5000:5000/tcp \
            -p 5060:5060/tcp \
            -p 5060:5060/udp \
            --env-file .env \
            --name voice-bot-container \
            --restart always \
            ${{ secrets.DOCKER_USERNAME }}/agent-stream-voice-agent:latest
